Repository bwmarrin/discordgo, pull requests merged in 2022-04, with the labels that each got.

#1150 Added Guild Members Search Function
  endpoints.go
  restapi.go
Labels: feature

#1152 Fix RateLimitPerUser on ChannelEdit
  structs.go
Labels: bug, breaking changes

#1153 Implement GuildEmoji
  restapi.go
Labels: feature

#1125 Add ApplicationID field to Interaction
  examples/components/main.go
  examples/context_menus/main.go
  examples/slash_commands/main.go
  interactions.go
  restapi.go
Labels: breaking changes

#1030 fix shadowed variables that were preventing errors from being returned properly
  restapi.go
  state.go
Labels: bug

#1151 Add option to disable rate-limited request retry
  discord.go
  restapi.go
  structs.go
Labels: high priority

#1158 feat: Add support of Stage Instance RestAPI and Events
  endpoints.go
  eventhandlers.go
  events.go
  examples/stage_instance/main.go
  restapi.go
  structs.go
Labels: feature, high priority

#1022 Modify GuildEmojiEdit function of restapi.go
  restapi.go
Labels: breaking changes

#1162 Custom JSON marshal/unmarshal functions
  components.go
  restapi.go
  structs.go
  util.go
Labels: feature

#1075 Application commands: Permissions v2
  eventhandlers.go
  events.go
  examples/slash_commands/main.go
  interactions.go
  restapi.go
  structs.go
Labels: feature, breaking changes
