Repository bwmarrin/discordgo, pull requests merged in 2022-07, with the labels that each got.

#1206 Interaction application permissions
  interactions.go
Labels: feature

#1201 Auto moderation
  endpoints.go
  eventhandlers.go
  events.go
  examples/auto_moderation/main.go
  restapi.go
  structs.go
Labels: feature

#1208 Application command options: min and max length
  interactions.go
Labels: feature, high priority

#1211 fix typo in InviteTargetEmbeddedApplication
  discord.go
  logging.go
  state.go
  structs.go
Labels: breaking changes

#1199 Allow setting bool fields of `ChannelEdit` to false
  examples/threads/main.go
  structs.go
Labels: bug, high priority, breaking changes
