Repository bwmarrin/discordgo, pull requests merged in 2022-10, with the labels that each got.

#1237 fix(interactions): incorrect call of State.Role in RoleValue()
  interactions.go
Labels: bug

#1254 fix(structs): fix type of `GuildScheduledEvent*` enum values
  structs.go
Labels: bug

#1256 fix(MultipartBodyWithJSON): form file field name format
  util.go
Labels: bug

#1262 fix: remove embedfield omitempty
  message.go
Labels: semver ignore

#1260 Continue to next packet if received broken packet
  voice.go
Labels: bug

#1227 Add missing fields to Ready
  events.go
  state.go
Labels: feature
