Repository bwmarrin/discordgo, pull requests merged in 2022-06, with the labels that each got.

#1198 add Invite ExpiresAt field
  structs.go
Labels: feature

#1196 Add support for `with_localizations` flag
  restapi.go
Labels: feature

#1191 Fix GuildTemplate struct and documentation
  structs.go
Labels: breaking changes

#1193 add GET prefix for ApplicationCommands bucketID
  restapi.go
Labels: bug
