Repository bwmarrin/discordgo, pull requests merged in 2022-02, with the labels that each got.

#1087 Dropping user account endpoints and functionality
  discord.go
  discord_test.go
  endpoints.go
  restapi.go
  restapi_test.go
Labels: Feedback Wanted

#1095 Add get guild stickers support
  message.go
  structs.go
Labels: enhancement

#1032 Add Guild Scheduled Event Support
  discord_test.go
  endpoints.go
  eventhandlers.go
  events.go
  examples/scheduled_events/main.go
  examples/threads/main.go
  restapi.go
  structs.go
Labels: feature, high priority
