Repository bwmarrin/discordgo, pull requests merged in 2022-08, with the labels that each got.

#1002 Add omitempty to channel_id in MessageReference struct
  message.go
Labels: bug

#1179 Add `Dialer` property to `Session`
  discord.go
  structs.go
  wsapi.go
Labels: feature, feedback

#1220 Use Dialer for Voice connections
  voice.go
Labels: feature

#1223 GuildFeatures added to UserGuild
  structs.go
Labels: breaking changes

#1225 Remove remaining undocumented structs and fields
  eventhandlers.go
  events.go
  structs.go
Labels: breaking changes

#1217 REST methods cleanup
  restapi.go
  structs.go
Labels: feature, high priority, breaking changes
