Repository bwmarrin/discordgo, pull requests merged in 2022-05, with the labels that each got.

#1177 fix: type of AuditLogActionApplicationCommandPermissionUpdate
  structs.go
Labels: breaking changes

#1174 make WebhookEdit fields pointers
  examples/slash_commands/main.go
  webhook.go
Labels: feature, breaking changes

#1166 fix: check if opus created
  voice.go
Labels: bug

#1182 Fix build error of examples/voice_receive
  examples/voice_receive/main.go
Labels: bug
